# Generated by Django 5.2.5 on 2025-09-25 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos',
            old_name='title',
            new_name='nombre',
        ),
    ]
