# Generated by Django 5.2.5 on 2025-09-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0004_rename_title_datos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='descripcion',
            field=models.CharField(),
        ),
    ]
