# Generated by Django 5.2.5 on 2025-09-25 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0005_alter_datos_descripcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datos',
            old_name='descripcion',
            new_name='apellido',
        ),
    ]
