# Generated by Django 5.2.5 on 2025-09-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0006_rename_descripcion_datos_apellido'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='cargo_empleado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
