# Generated by Django 5.2.5 on 2025-09-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0007_datos_cargo_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
