# Generated by Django 5.2.5 on 2025-09-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0008_datos_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='cedula',
            field=models.DateField(blank=True, max_length=20, null=True),
        ),
    ]
