# Generated by Django 5.2.5 on 2025-09-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0009_alter_datos_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='datos',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datos',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
