# Generated by Django 5.2.5 on 2025-09-25 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0010_datos_fecha_ingreso_datos_salario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='cedula',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='fecha_ingreso',
            field=models.DateField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='datos',
            name='salario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
