# Generated by Django 5.2.5 on 2025-09-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0012_alter_datos_apellido_alter_datos_cedula_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='cedula',
            field=models.CharField(default='', max_length=10),
        ),
    ]
