# Generated by Django 5.2.5 on 2025-09-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0013_alter_datos_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos',
            name='cedula',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
